### ISSUE TITLE
Support creating subclasses of PolyField instead of passing functions as arguments

### ISSUE THREAD

**Issue by chrisphilip322** [Bachmann1234/marshmallow-polyfield#11]
I've created a fork of this project to add the ability to create instances of `PolyField` by creating classes rather than through passing functions to the `PolyField` constructor (see link below). My use case is with `marshmallow~=2.0` which is why I have branched off of v3.2 of marshmallow-polyfield. My suggestion is to create a new release branch here for updating marshmallow-3.X and then I can pull my changes here. I would be willing also to make sure these changes are compatible with HEAD of master but as I said my particular use case is only for `marshmallow~=2.0`. I have left the pull request open on my fork in case there is any changes any one would like to request.

https://github.com/macbeth322/marshmallow-polyfield/pull/1

**Comment by chrisphilip322** [comment]
I went ahead and merged my PR so hopefully it can get merged in here as well. @Bachmann1234 ?

**Comment by Bachmann1234** [comment]
Sure thing, open up a PR here and ill give it a more detailed look.  Ill take your advise and then see if I can find the time to investigate if the two brances can be brought together.

**Comment by Bachmann1234** [comment]
https://github.com/Bachmann1234/marshmallow-polyfield/tree/marshmallow-3.X Open the PR against this one

**Comment by Bachmann1234** [comment]
This is merged. I think im going to go ahead and release master. Sometime in the next couple days
