### ISSUE TITLE
Are there plans to relase version 4.0 to pypi?

### ISSUE THREAD

**Issue by delapuente** [Bachmann1234/marshmallow-polyfield#13]
When installing `marshmallow-polyfield` from `pip`, it is installing version `3.2`. Are you planning to release version `4.0` as well?

**Comment by Bachmann1234** [comment]
aw jeez, yeah ill look into this. Hopefully tonight

**Comment by Bachmann1234** [comment]
Ok, it had been a while. I looked into this and remembered why I never released it.

version 4 is for marshmallow 3. Which has not released a non beta version yet.

**Comment by sloria** [comment]
An update on marshmallow 3: 

> A stable release of marshmallow 3 is on the horizon! marshmallow 3 is already a massive improvement on version 2, and we're focused on cutting the final release as soon as we can. I estimate that we'll have the a release candidate within the next month. You can follow our progress here: https://github.com/marshmallow-code/marshmallow/milestones .

> All projects within the marshmallow-code GitHub organization have been made compatible with marshmallow 3

https://opencollective.com/marshmallow/updates/how-your-donations-are-used

Even though marshmallow 3 is still in beta, we are still recommending it for new projects and are trying to get the ecosystem up to date.

**Comment by Bachmann1234** [comment]
Released a version 5 that requires Masrshmallow 3.0
