### ISSUE TITLE
Release new version to support marshmallow~=2.0

### ISSUE THREAD

**Issue by chrisphilip322** [Bachmann1234/marshmallow-polyfield#20]
The PR #12 is setup to support marshmallow~=2.0 with the changes added in #14. Is it possible to release a new version with those changes?

**Comment by Bachmann1234** [comment]
Yeah, I can reopen that PR

**Comment by Bachmann1234** [comment]
If you think its ready ill review, merge, and when I get some time. Hopefully this week

**Comment by Bachmann1234** [comment]
I just want to confirm my understanding since at this point you likely know better than I do :-P

This PR will support marshmallow 2 but is *not* a version that supports 2 and 3. Right? 

Just wanna confirm that I should not merge this into master but keep it as a branch (PR points to a branch that I will likely rename)

**Comment by chrisphilip322** [comment]
Thanks for taking another look at this. Yes, #12 supports marshmallow 2 but not marshmallow 3. There are breaking changes between them, but since marshmallow 3 hasn't been fully releaseed yet (only beta packages) we don't want to migrate over to that version yet; which is why I want a version of this library to support marshmallow 2.

So to confirm, this should *not* go into master branch since it does not support marshmallow 3.

**Comment by Bachmann1234** [comment]
Cool, ill get this done and update the readme for people.

**Comment by Bachmann1234** [comment]
Oy had some trouble with this. I think its because I had already pulled a few versions from pypi.

But here it is https://pypi.org/project/marshmallow-polyfield/4.2/

The marshmallow 2.0 branch is https://github.com/Bachmann1234/marshmallow-polyfield/tree/polyfield-2support

**Comment by chrisphilip322** [comment]
Sweet! Thanks for taking the time to do this!
