### ISSUE TITLE
Dynamic field or dynamic schema - how to deal with marshmallow's `exclude`, `only`, `load_only` ...``

### ISSUE THREAD

**Issue by kevinadda** [Bachmann1234/marshmallow-polyfield#25]
Hello,

I am currently using polyfield (thanks!) but I am having troubles understanding what it precisely is and if I can rely on it in the end. 

**What I'm trying to do** 
I have a DB collection with both products and brands stored. They don't have the same model, therefore I implemented 2 different schemas for them.
Now in another schema, I want to serialize a list of such items (products or brands). 

**How I do it**
Using polyfield and marshmallow, it looks like:
```
class BrandSchema(Schema):
    name = fields.String()
    organization_name = fields.String()


class ProductSchema(Schema):
    name = fields.String()
    brand = fields.Nested(BrandSchema())


class ProductOrBrandGroupSchema(Schema):
    name = fields.String()
    items = fields.List(Polyfield(
        serialization_schema_selector=...,
        deserialization_schema_selector=...,
        required=True,
    ))
```
This works fine.
One thing to note, in the situation where `items` are only products, we would use a nested field:
`items = fields.List(fields.Nested(fields.Product( ....`

**The problem**
Now I have another schema that nests this last one:
```
class MySchema(Schema):
    group = fields.Nested(ProductOrBrandGroupSchema())
    name = fields.String()
```

I want to exclude `items` when serializing `MySchema`. Say I have an instance `my_schema`, I use:
```
MySchema(exclude=['group.items']).dump(my_schema)
```

This will return the serialization **but will not exlude `items`** : hence, `exclude` with dot notation is for nested schemas.

**The question**
`Polyfield` looks like a field, however its two selector methods returns schemas. If it were a schema, I could write `fields.List(fields.Nested(Polyfield(...` but this does not work.

Do you see a way of doing this? Have you seen an implementation of `Polyschema`? Is this what `Polyfield` should actually be?

I hope this is clear enough. Thanks!

**Comment by Bachmann1234** [comment]
Howdy! Thanks for the detail. I want to give this the time it needs but I will not be able to for roughly a week. I'm currently on my honeymoon followed by starting a new job so things are a bit hectic. I will try to take a look by mid week.

**Comment by kevinadda** [comment]
Enjoy!
I will have to find a solution for the short term, I'll put it here if it can help.

**Comment by Bachmann1234** [comment]
Hey, so looking at this im starting to think it could be a bug in polyfield. 

But It looks like some versions of marshmallow have had issues with exclude and nested fields (without this plugin... just in general. See this older issue https://github.com/marshmallow-code/marshmallow/issues/672 )

What version of marshmallow are you using?

**Comment by kevinadda** [comment]
I am using 3.0.0rc5, which is fairly recent.

To me however, the problem cannot be solved by marshmallow itself, as there is currently no way to dynamically pass exclude fields to a schema through a polyfield.

**Comment by better-world-io** [comment]
I came accross [this lib](https://github.com/marshmallow-code/marshmallow-oneofschema) that does precisely what I was looking for.
The proposed meta schema object can be used as a schema : it can be inputted in `Nested`, handles `many` and `only`, ... and probably the rest of marshmallow's `Schema` features.

Thanks for your help!

**Comment by kevinadda** [comment]
I came accross [this lib](https://github.com/marshmallow-code/marshmallow-oneofschema) and it does precisely what I was looking for.

The proposed meta schema object can be used as a schema : it can be inputted in `Nested`, handles `many` and `only`, ... and probably the rest of marshmallow's schema features.

Thanks for your help!
