### ISSUE TITLE
Access parent data in serialization/deserialization schema selector

### ISSUE THREAD

**Issue by jiribires** [Bachmann1234/marshmallow-polyfield#3]
I've few use cases where access to parent object is needed for choosing schema.
Would you consider adding parent object/dictionary to schema selectors?

**Comment by Bachmann1234** [comment]
Can you give me more detail? Im not 100% sure I get what you are looking for

**Comment by jiribires** [comment]
Type information is not in field itself, but in class `Foo`:

```
class Foo:
    type = 'image'  # image or video
    extra = {
        'height': 640,
        'width': 480
    }
```

Schema selectors need access to `Foo.type` field.
I've modified poylyfield in my fork https://github.com/jiribires/marshmallow-polyfield.

**Comment by Bachmann1234** [comment]
@jiribires why not go ahead and open a PR. Ill probably merge it. I dont think I have a ton of users so I am not too worried about api breaking for something reasonable like this.

And I would go ahead and increment the major version to clarify this. 

If you are willing to do this could you update the Readme before making the PR?

**Comment by jiribires** [comment]
Changes are in PR #4
