### ISSUE TITLE
Published wheel and sdist install tests package

### ISSUE THREAD

**Issue by mtreinish** [Bachmann1234/marshmallow-polyfield#38]
When you install marshmallow-polyfield from PyPI right now in addition to the expected `marshmallow_polyfield` namespace an additional  python package named `tests` gets installed.
This seems like a return of the same issue from #23

For example you can run:

```bash
virtualenv polyfield-test
polyfield-test/bin/pip install marshmallow-polyfield
polyfield-test/bin/python -c 'from tests import shapes; shapes.Triangle()'
```

which will return a TypeError because of the missing arguments (but shows that the marshmallow-polyfield tests are getting installed as a separate package):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__() missing 3 required positional arguments: 'color', 'base', and 'height'
```

The package shouldn't be populating a second namespace for tests.

**Comment by Bachmann1234** [comment]
Howdy! Can you confirm your python version? I think you are running 3x. I can only reproduce this in 3

```
venv ❯ python
Python 2.7.17 (default, Dec 23 2019, 21:25:33)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tests
>>> from tests import shapes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tests
```


```
venv ❯ python
Python 3.8.1 (default, Jan 23 2020, 11:19:51)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tests import shapes
>>> shapes
<module 'tests.shapes' from '/Users/bachmann/Desktop/venv/lib/python3.8/site-packages/tests/shapes.py'>
>>>
```

**Comment by Bachmann1234** [comment]
@mtreinish try https://pypi.org/project/marshmallow-polyfield/5.9/ and let me know if that works for you

**Comment by mtreinish** [comment]
Yeah, I was using python 3.8. And the 5.9 release has fixed the issue. Thanks
